### ISSUE TITLE
Illegal Haskell construct encountered

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#316]
When I try to promote:
```haskell
$(promoteOnly [d|
    replaceAllGTypes :: (a -> Type -> a) -> [Type] -> [a] -> [a]
    replaceAllGTypes f types as = zipWith f as types
  |])
```
I am greeted with
```haskell
    Illegal Haskell construct encountered:
headed by: DStarT
applied to: []
   |
94 | $(promoteOnly [d|
   |   ^^^^^^^^^^^^^^^...

/Users/LeanderK/Documents/Haskell/Earhart/src/V4/TypeHelpers.hs:94:3: error:
    Q monad failure
   |
94 | $(promoteOnly [d|
   |   ^^^^^^^^^^^^^^^...
Failed, no modules loaded.
```
I don't see anything illegal here? Am I missing something?

EDIT: Same for
```haskell
$(promoteOnly [d|
    toTypes :: [(x, Type)] -> [Type]
    toTypes = map snd
  |])
```

**Comment by RyanGlScott** [comment]
Strange, I don't get any such error when I try this:

```haskell
{-# LANGUAGE GADTs #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE UndecidableInstances #-}
module Foo where

import Data.Kind
import Data.Singletons.Prelude
import Data.Singletons.TH

$(promoteOnly [d|
    replaceAllGTypes :: (a -> Type -> a) -> [Type] -> [a] -> [a]
    replaceAllGTypes f types as = zipWith f as types
  |])
```

Can you post the full code you're using?

**Comment by LeanderK** [comment]
hmm same error for me when I isolate to `Foo`.
I am using stack with `ghc-8.4.1`
```yaml
resolver: ghc-8.4.1
compiler: ghc-8.4.1
compiler-check: match-exact

extra-deps: 
- eliminators-0.4.1
#because 8.4 is not lts yet
- extra-1.6.4
- singleton-nats-0.4.0.4
- th-abstraction-0.2.6.0
- clock-0.7.2
- singletons-2.4.1
- syb-0.7
- th-desugar-1.8
- th-expand-syns-0.4.4.0
- th-lift-0.7.8
- th-orphans-0.13.5
- th-lift-instances-0.1.11
- th-reify-many-0.1.8
- safe-0.3.17
- vector-0.12.0.1
- primitive-0.6.3.0
```
